### PR TITLE
Add Recording Group to PVR API 1.9.7

### PR DESCRIPTION
**Pull request by metaron-uk**
**@ksooo**: Here's the promised pull request.
screenshot000
screenshot001

Only the latest commit is of interest, the previous two were to rebase onto current 'pvr-series-recordings' (it wouldn't pull without a manual merge, so i guess a force or two were necessary).

I've decided that as you will have comments, it's best to submit the PR now. If I try and rebase again you probably won't see anything until tomorrow evening (git novice here)!

You'll notice I also worked out how 'Lifetime' could be tweaked to support non-integer settings along the way.

I've tested this against a nasty hack to the pvr.hts code which I've pushed to the folderList branch of https://github.com/metaron-uk/pvr.hts.git. Currently it exercises the API effectively, but doesn't actually command the backend based on the Recording Group setting.

I'm re-compiling with the rebased code and continuing to hack at my pvr.hts fork to see if I can get something that actually affects the backend. When I do I'll push another commit to my repository on the folderList branch in case you find it useful for testing.

### CODE REVIEW

**Comment by ksooo** [comment]
@metaron-uk  Excellent! And you are damn fast. I will pull this into xbmc PR 7079 as it is, no further comments (there is only one whitespace glitch). This is exactly as I would have written the code. ;-) Many thanks.

Note: I will not exactly pull this, but reassign your changes to the different existing "logical" commits of PR 7079 as those chunks get reviewed by different people.

**Comment by metaron-uk** [comment]
**@ksooo** That's excellent news and many thanks for the compliments.
I'm looking forward to playing with Janbar's 1.9.7 mythtv implementation :-)
For now I'll go and poke my nose in some other part of kodi's code.
Or maybe I'll just try to understand git rebase....

**Comment by ksooo** [comment]
@metaron-uk Merged manually into pvr-series-recordings branch. Closing this PR. Many thanks once again.

BTW: I force pushed the changes. So, please take care. Easiest way is to do a new clone of my xbmc clone.

**Comment by ksooo** [comment]
@janbar you might be interested in this latest api extension as it allows pvr.mythtv to support recording groups. If you re pull 7079 you will get  the respective code changes.

**Comment by janbar** [comment]
@ksooo thanks, i get it

**Pull request closed without merging**
